
# Config file for Telegram Captcha Bot

# Button text
button_text = "Я не робот!"

# Bot sends this message to new users
welcome_message = "Привет! Это наш способ защититься от ботов, просьба отнестись с пониманием. Пожалуйста, нажми на кнопку ниже в течение минуты иначе будешь забанен!"

# Edit welcome message with this text if user passed validation
after_success_message = "Пользователь справился"

# Edit welcome message with this text if user failed validation
after_fail_message = "Пользователь не справился и был забланен"

# Show success and failure messages or delete them. Pick "show" or "del"
print_success_and_fail_messages_strategy = "del"

# During this time in seconds, the new user have to press the captha button
welcome_timeout = "90"

# If the new user does not press the button, the bot will ban the user for this duration of time. Can be "forever" or number of minutes ("10")
ban_duration = "10"

# Do you want to use a socks5 proxy server? Can be "yes" or "no"
use_socks5_proxy = "no"

# Socks5 proxy server IP address
socks5_address = "1.1.1.1"

# Socks5 proxy server TCP port
socks5_port = "1080"

# Socks5 proxy server username
socks5_login = "login"

# Socks5 proxy server password
socks5_password = "password"
